#!/bin/bash
###########################################
# this is my first script 
# date 1/8//19
##########################################

#NAME="Manisha" 


for i in $@
do
      printf "%s\n" " Hi $i" 

done 

#echo Hi $1 and $2
#echo  'this is my  $0' 
#printf "%s\t"  "hi there" 
#printf "%s\n" " how are you?"
exit 0
